### ISSUE TITLE
In Paper, A Mathematical Theory of Danksharding, how to understand rbo

### ISSUE THREAD

**Issue by cliff0412** [ingonyama-zk/papers#10]
Refer to paper A Mathematical Theory of Danksharding.

in this definition
 u_{\mu} \equiv u^{rbo(\mu)} 

how to understand rbo?

for example, what would the output of rbo(11) be?

**Comment by yuvalingo** [comment]
rob is reversed-bit-order
'd11 = 'b1011
so rob('b1011) = 'b(1101) = 'd13

**Comment by cliff0412** [comment]
thanks for the explanation. for example, if it is 4 bits number, then it will access {0,8,4,12,2,10,6,14} and then {1,9,5,13,3,11,7,15}. the even and odd cosets alright? and the order does not matter?

**Comment by yuvalingo** [comment]
exactly. also, if you want cosets of order 4 you'll have {0,8,4,12}, {2,10,6,14}, etc
