### ISSUE TITLE
danksharding paper data interpolation question

### ISSUE THREAD

**Issue by cliff0412** [ingonyama-zk/papers#8]
easy to understand that each data point is an evaluation of a 2 D polynomial; however, how to understand it is aan evaluation of two 1 D polynomials. is it to take the product of the two evaluations?

**Comment by ImmanuelSegol** [comment]
@krakhit

**Comment by yuvaldomb** [comment]
It's an evaluation of a 2d poly. Evaluating it by rows and then by columns is just a method to achieve this. It's pretty standard. Look up methods to calc 2d ftt
